stages:
  create_manifest:
    cmd: python scripts/create_manifest.py
    deps:
    - scripts/create_manifest.py
    - data/raw/en/
    outs:
    - data/manifests/en/clean.jsonl

  phoneme_conversion:
    cmd: python scripts/phoneme_conversion.py
    deps:
    - scripts/phoneme_conversion.py
    - data/manifests/en/clean.jsonl
    outs:
    - data/manifests/en/phonemes.jsonl

  noise_injection:
    cmd: python scripts/noise_injection.py
    deps:
    - scripts/noise_injection.py
    - data/manifests/en/phonemes.jsonl
    outs:
    - data/manifests/en/noisy.jsonl

  inference:
    cmd: python scripts/inference.py
    deps:
    - scripts/inference.py
    - data/manifests/en/noisy.jsonl
    outs:
    - data/manifests/en/hypotheses.jsonl

  merge_hi:
    cmd: cat results/hi_whisper_chunk1.jsonl results/hi_whisper_chunk2.jsonl 
      results/hi_whisper_chunk3.jsonl results/hi_whisper_chunk4.jsonl 
      results/hi_whisper_chunk5.jsonl results/hi_whisper_chunk6.jsonl > 
      results/hi_whisper_full.jsonl
    deps:
    - results/hi_whisper_chunk1.jsonl
    - results/hi_whisper_chunk2.jsonl
    - results/hi_whisper_chunk3.jsonl
    - results/hi_whisper_chunk4.jsonl
    - results/hi_whisper_chunk5.jsonl
    - results/hi_whisper_chunk6.jsonl
    outs:
    - results/hi_whisper_full.jsonl

