stages:
  create_manifest:
    cmd: python scripts/create_manifest.py
    deps:
      - scripts/create_manifest.py
    outs:
      - data/manifests/en/clean.jsonl

  text_to_phonemes:
    cmd: python scripts/text_to_phonemes.py
    deps:
      - scripts/text_to_phonemes.py
      - data/manifests/en/clean.jsonl
    outs:
      - data/manifests/en/phonemes.jsonl

  add_noise:
    cmd: python scripts/add_noise.py
    deps:
      - scripts/add_noise.py
      - data/manifests/en/phonemes.jsonl
    outs:
      - data/manifests/en/noisy.jsonl

  inference:
    cmd: python scripts/inference.py
    deps:
      - scripts/inference.py
      - data/manifests/en/noisy.jsonl
    outs:
      - data/manifests/en/hypotheses.jsonl
